name = "facebook-page-approval"
main = "src/index.ts"
compatibility_date = "2026-08-08"

[[kv_namespaces]]
binding = "DRAFTS"
id = "0771efc0a7304a7aa2f83a118a86269a"

[vars]
DISCORD_CHANNEL_ID = "1535565515572117576"
